Change mechanism to find an installation of foonathan_memory
eProsima/foonathan_memory_vendor pull request #67
Opened 2023-10-24 06:04 UTC by richiware

With current implementation once foonathan_memory is compiled for a certain configuration (Release, Debug..) using colcon, changing to another compilation doesn't make it compile, because the previous one is found on CMAKE_INSTALL_PREFIX.

With new implemenation, this behaviour is fixed, but it is still be able to find an installed foonathan_memory.

Tested on Windows, Linux and Mac.

2023-10-24 09:38 UTC, MiguelCompany requested changes

2023-10-24 09:38 UTC, MiguelCompany commented on CMakeLists.txt
>  project(foonathan_memory_vendor VERSION "1.3.1")
Please bump this to `1.3.2`, and reference this PR on CHANGELOG.rst

2023-10-24 14:25 UTC, richiware commented
Done in bb87886

2023-10-25 05:29 UTC, MiguelCompany approved these changes

2023-10-25 05:50 UTC, merged