Add FORCE_BUILD option to cmake
eProsima/foonathan_memory_vendor pull request #69
Opened 2024-03-07 15:33 UTC by xavisolesoft

This PR fixes the next issue the next issue:
https://github.com/eProsima/Fast-DDS/discussions/4528

2024-03-11 12:01 UTC, JesusPoderoso requested changes
Hi @xavisolesoft, thanks for your contribution!
These are a couple of suggestions:

2024-03-11 12:01 UTC, JesusPoderoso commented on CMakeLists.txt
> +option(FORCE_BUILD "Force this package build even is already installed in the system" OFF)
```suggestion
option(FOONATHAN_MEMORY_FORCE_VENDORED_BUILD "Force foonathan memory vendor package build even it is already installed in the system" OFF)
```

2024-03-11 12:01 UTC, JesusPoderoso commented on CMakeLists.txt
> +if(FORCE_BUILD EQUAL OFF)
```suggestion
if(FOONATHAN_MEMORY_FORCE_VENDORED_BUILD EQUAL OFF)
```

2024-03-11 16:44 UTC, xavisolesoft commented on CMakeLists.txt
> +if(FORCE_BUILD EQUAL OFF)
I committed all suggested changes

2024-03-12 08:47 UTC, JesusPoderoso requested changes
Hi @xavisolesoft, I missed a small nitpick here.
This PR goes in once applied!

2024-03-12 08:47 UTC, JesusPoderoso commented on CMakeLists.txt
> +option(FOONATHAN_MEMORY_FORCE_VENDORED_BUILD "Force foonathan memory vendor package build even it is already installed in the system" OFF)
```suggestion
option(FOONATHAN_MEMORY_FORCE_VENDORED_BUILD "Force foonathan memory vendor package build even if it is already installed in the system" OFF)
```

2024-03-12 10:04 UTC, xavisolesoft commented
> Hi @xavisolesoft, I missed a small nitpick here. This PR goes in once applied!

Fixed, thank you!

2024-03-12 10:20 UTC, JesusPoderoso approved these changes
Thank you @xavisolesoft for your contribution!

LGTM

2024-03-12 10:21 UTC, merged